// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuqBEyzJP-vHrmHkV_U9SrYdHTL2DDXxA',
    appId: '1:274808682894:web:2c59690e41b2eee6cf8cdf',
    messagingSenderId: '274808682894',
    projectId: 'agrisaathi-ab280',
    authDomain: 'agrisaathi-ab280.firebaseapp.com',
    storageBucket: 'agrisaathi-ab280.firebasestorage.app',
    measurementId: 'G-2V2ZKQLSLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHxDZ2K5Ok1dReHty-WShbX-CDELefQiQ',
    appId: '1:274808682894:android:19e80973e256b3a3cf8cdf',
    messagingSenderId: '274808682894',
    projectId: 'agrisaathi-ab280',
    storageBucket: 'agrisaathi-ab280.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNGAmcn0ItUICfD8PIt_C-0-LIxbrshvw',
    appId: '1:274808682894:ios:452655b22725d8a1cf8cdf',
    messagingSenderId: '274808682894',
    projectId: 'agrisaathi-ab280',
    storageBucket: 'agrisaathi-ab280.firebasestorage.app',
    iosBundleId: 'com.example.agriSaathi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNGAmcn0ItUICfD8PIt_C-0-LIxbrshvw',
    appId: '1:274808682894:ios:452655b22725d8a1cf8cdf',
    messagingSenderId: '274808682894',
    projectId: 'agrisaathi-ab280',
    storageBucket: 'agrisaathi-ab280.firebasestorage.app',
    iosBundleId: 'com.example.agriSaathi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuqBEyzJP-vHrmHkV_U9SrYdHTL2DDXxA',
    appId: '1:274808682894:web:e0ee33f38da4942fcf8cdf',
    messagingSenderId: '274808682894',
    projectId: 'agrisaathi-ab280',
    authDomain: 'agrisaathi-ab280.firebaseapp.com',
    storageBucket: 'agrisaathi-ab280.firebasestorage.app',
    measurementId: 'G-EM5N7QHLNW',
  );
}
